language: node_js
node_js:
    - 10
cache:
    directories:
        - ~/.npm
jobs:
    include:
        - stage: test
          script:
              - npm run validate
        - stage: deploy
          if: branch = master
          script:
              - npm config set access public
              - npm run validate
              - npm run semantic-release
              - npm run publish:coverage
